ecommerce_orders_dataset

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("C:/Users/Lenovo/OneDrive/Desktop/ds/Dataset/ecommerce_orders_dataset.csv")

In [7]:
# find Top 10 Datas from the csv file
df.head(10)

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
0,615717,CUST007322,2023-01-01,2023,1,1,Sunday,1,32,Male,...,2,Delivered,No,4.4,2144.92,23.10,15.75,Winter,No,No
1,626919,CUST004717,2023-01-01,2023,1,1,Sunday,1,50,Male,...,9,Delivered,No,4.1,817.17,8.57,3.32,Winter,No,No
2,615781,CUST004415,2023-01-01,2023,1,1,Sunday,1,61,Male,...,2,Delivered,No,5.0,541.16,29.72,45.67,Winter,No,No
3,621747,CUST004114,2023-01-01,2023,1,1,Sunday,1,34,Male,...,6,Returned,Yes,3.4,700.49,25.22,75.25,Winter,No,No
4,625881,CUST000145,2023-01-01,2023,1,1,Sunday,1,37,Male,...,8,Delivered,No,3.6,2133.77,24.64,26.06,Winter,No,No
5,613497,CUST000940,2023-01-01,2023,1,1,Sunday,1,32,Female,...,5,Processing,No,4.1,5844.78,30.29,125.38,Winter,No,Yes
6,600746,CUST004139,2023-01-01,2023,1,1,Sunday,1,25,Female,...,6,Delivered,No,5.0,1178.52,27.91,32.45,Winter,No,No
7,604774,CUST000543,2023-01-01,2023,1,1,Sunday,1,38,Female,...,6,Delivered,No,4.1,2535.68,10.14,11.85,Winter,No,No
8,600323,CUST003309,2023-01-01,2023,1,1,Sunday,1,48,Female,...,5,Delivered,No,3.4,598.88,17.93,19.06,Winter,No,No
9,608449,CUST006419,2023-01-01,2023,1,1,Sunday,1,31,Other,...,6,Shipped,No,4.5,1050.17,31.95,59.20,Winter,No,No

In [8]:
df.shape

(30000, 41)

In [9]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Order_Date', 'Year', 'Month', 'Day',
       'Day_Of_Week', 'Quarter', 'Customer_Age', 'Customer_Gender', 'Country',
       'City', 'Customer_Segment', 'Product_ID', 'Product_Category',
       'Product_Subcategory', 'Brand', 'Unit_Price', 'Quantity',
       'Discount_Percent', 'Discount_Amount', 'Coupon_Used', 'Shipping_Cost',
       'Tax_Amount', 'Order_Amount', 'Payment_Method', 'Device_Type',
       'Traffic_Source', 'Membership_Status', 'Shipping_Method',
       'Warehouse_Region', 'Delivery_Days', 'Order_Status', 'Returned',
       'Review_Rating', 'Customer_Lifetime_Value', 'Profit_Margin_Percent',
       'Profit_Amount', 'Season', 'Holiday_Season', 'High_Value_Order'],
      dtype='object')

In [20]:
df["Customer_Gender"].head(20)

0       Male
1       Male
2       Male
3       Male
4       Male
5     Female
6     Female
7     Female
8     Female
9      Other
10    Female
11    Female
12    Female
13      Male
14      Male
15    Female
16      Male
17    Female
18      Male
19      Male
Name: Customer_Gender, dtype: object

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order_ID                 30000 non-null  int64
 1   Customer_ID              30000 non-null  object
 2   Order_Date               30000 non-null  object
 3   Year                     30000 non-null  int64
 4   Month                    30000 non-null  int64
 5   Day                      30000 non-null  int64
 6   Day_Of_Week              30000 non-null  object
 7   Quarter                  30000 non-null  int64
 8   Customer_Age             30000 non-null  int64
 9   Customer_Gender          30000 non-null  object
 10  Country                  30000 non-null  object
 11  City                     30000 non-null  object
 12  Customer_Segment         30000 non-null  object
 13  Product_ID               30000 non-null  object
 14  Product_Category         30000 non-null  object
 15  Product_Subcategory      30000 non-null  object
 16  Brand                    30000 non-null  object
 17  Unit_Price               30000 non-null  float64
 18  Quantity                 30000 non-null  int64
 19  Discount_Percent         30000 non-null  int64
 20  Discount_Amount          30000 non-null  float64
 21  Coupon_Used              30000 non-null  object
 22  Shipping_Cost            30000 non-null  float64
 23  Tax_Amount               30000 non-null  float64
 24  Order_Amount             30000 non-null  float64
 25  Payment_Method           30000 non-null  object
 26  Device_Type              30000 non-null  object
 27  Traffic_Source           30000 non-null  object
 28  Membership_Status        30000 non-null  object
 29  Shipping_Method          30000 non-null  object
 30  Warehouse_Region         30000 non-null  object
 31  Delivery_Days            30000 non-null  int64
 32  Order_Status             30000 non-null  object
 33  Returned                 30000 non-null  object
 34  Review_Rating            30000 non-null  float64
 35  Customer_Lifetime_Value  30000 non-null  float64
 36  Profit_Margin_Percent    30000 non-null  float64
 37  Profit_Amount            30000 non-null  float64
 38  Season                   30000 non-null  object
 39  Holiday_Season           30000 non-null  object
 40  High_Value_Order         30000 non-null  object
dtypes: float64(9), int64(9), object(23)
memory usage: 9.4+ MB

In [23]:
df["Customer_Gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [25]:
df["Customer_Segment"].head(10)

0        Loyal
1    Returning
2    Returning
3    Returning
4      Premium
5          New
6    Returning
7      Premium
8    Returning
9    Returning
Name: Customer_Segment, dtype: object

In [27]:
df["Customer_Segment"].unique()

array(['Loyal', 'Returning', 'Premium', 'New'], dtype=object)

In [29]:
df["Country"].describe()

count      30000
unique        10
top       Canada
freq        3099
Name: Country, dtype: object

Task1 - Which Month sales is more in India

In [41]:
df.loc[df['Customer_ID'] == "CUST004415", 'Country']

2               India
131           Germany
406               UAE
20417             UAE
29034    Saudi Arabia
Name: Country, dtype: object

In [34]:
df[df["Country"] == "India"].head(10)

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
2,615781,CUST004415,2023-01-01,2023,1,1,Sunday,1,61,Male,...,2,Delivered,No,5.0,541.16,29.72,45.67,Winter,No,No
4,625881,CUST000145,2023-01-01,2023,1,1,Sunday,1,37,Male,...,8,Delivered,No,3.6,2133.77,24.64,26.06,Winter,No,No
11,628771,CUST002640,2023-01-01,2023,1,1,Sunday,1,63,Female,...,2,Cancelled,No,3.5,2278.80,20.77,39.76,Winter,No,No
32,602516,CUST004129,2023-01-02,2023,1,2,Monday,1,31,Female,...,6,Delivered,No,5.0,723.15,23.13,4.42,Winter,No,No
36,606625,CUST006843,2023-01-02,2023,1,2,Monday,1,24,Male,...,5,Cancelled,No,4.1,456.79,18.63,8.53,Winter,No,No
37,613453,CUST004116,2023-01-02,2023,1,2,Monday,1,46,Female,...,1,Delivered,No,3.6,1188.87,17.54,16.32,Winter,No,No
43,621506,CUST002437,2023-01-02,2023,1,2,Monday,1,20,Female,...,6,Delivered,No,5.0,780.74,11.05,6.69,Winter,No,No
57,609669,CUST007436,2023-01-03,2023,1,3,Tuesday,1,47,Male,...,7,Cancelled,No,3.6,2712.55,36.31,85.46,Winter,No,No
71,611974,CUST007663,2023-01-04,2023,1,4,Wednesday,1,44,Male,...,0,Delivered,No,4.1,6578.18,15.37,295.84,Winter,No,Yes
97,619796,CUST005785,2023-01-05,2023,1,5,Thursday,1,30,Female,...,3,Delivered,No,4.5,5760.27,32.31,124.76,Winter,No,No

In [42]:
india_df = df[df["Country"] == "India"]

In [43]:
india_df

,Order_ID,Customer_ID,Order_Date,Year,Month,Day,Day_Of_Week,Quarter,Customer_Age,Customer_Gender,...,Delivery_Days,Order_Status,Returned,Review_Rating,Customer_Lifetime_Value,Profit_Margin_Percent,Profit_Amount,Season,Holiday_Season,High_Value_Order
2,615781,CUST004415,2023-01-01,2023,1,1,Sunday,1,61,Male,...,2,Delivered,No,5.0,541.16,29.72,45.67,Winter,No,No
4,625881,CUST000145,2023-01-01,2023,1,1,Sunday,1,37,Male,...,8,Delivered,No,3.6,2133.77,24.64,26.06,Winter,No,No
11,628771,CUST002640,2023-01-01,2023,1,1,Sunday,1,63,Female,...,2,Cancelled,No,3.5,2278.80,20.77,39.76,Winter,No,No
32,602516,CUST004129,2023-01-02,2023,1,2,Monday,1,31,Female,...,6,Delivered,No,5.0,723.15,23.13,4.42,Winter,No,No
36,606625,CUST006843,2023-01-02,2023,1,2,Monday,1,24,Male,...,5,Cancelled,No,4.1,456.79,18.63,8.53,Winter,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29977,603865,CUST004741,2026-12-30,2026,12,30,Wednesday,4,35,Male,...,0,Shipped,No,3.0,8034.50,24.82,136.56,Winter,Yes,Yes
29981,619915,CUST000579,2026-12-31,2026,12,31,Thursday,4,49,Female,...,5,Returned,Yes,4.0,5550.30,15.80,77.43,Winter,Yes,Yes
29986,628484,CUST000076,2026-12-31,2026,12,31,Thursday,4,31,Female,...,4,Delivered,No,4.2,12287.04,14.83,111.66,Winter,Yes,Yes
29987,618435,CUST007265,2026-12-31,2026,12,31,Thursday,4,24,Male,...,6,Returned,Yes,3.2,1999.89,25.66,31.03,Winter,No,No
29991,608441,CUST004583,2026-12-31,2026,12,31,Thursday,4,41,Male,...,2,Delivered,No,4.3,1025.52,32.26,47.14,Winter,Yes,No

In [44]:
india_df.columns

Index(['Order_ID', 'Customer_ID', 'Order_Date', 'Year', 'Month', 'Day',
       'Day_Of_Week', 'Quarter', 'Customer_Age', 'Customer_Gender', 'Country',
       'City', 'Customer_Segment', 'Product_ID', 'Product_Category',
       'Product_Subcategory', 'Brand', 'Unit_Price', 'Quantity',
       'Discount_Percent', 'Discount_Amount', 'Coupon_Used', 'Shipping_Cost',
       'Tax_Amount', 'Order_Amount', 'Payment_Method', 'Device_Type',
       'Traffic_Source', 'Membership_Status', 'Shipping_Method',
       'Warehouse_Region', 'Delivery_Days', 'Order_Status', 'Returned',
       'Review_Rating', 'Customer_Lifetime_Value', 'Profit_Margin_Percent',
       'Profit_Amount', 'Season', 'Holiday_Season', 'High_Value_Order'],
      dtype='object')

In [45]:
india_monthly_sales_df = india_df.groupby("Month")["Order_Amount"].sum()

In [46]:
india_monthly_sales_df

Month
1      89317.68
2      88366.32
3     108274.56
4      83844.77
5      74509.89
6      95587.38
7     108526.85
8     102878.96
9     100061.57
10    100801.81
11     92200.71
12    100940.83
Name: Order_Amount, dtype: float64

In [50]:
india_monthly_sales_df.sort_values(ascending=False)

Month
7     108526.85
3     108274.56
8     102878.96
12    100940.83
10    100801.81
9     100061.57
6      95587.38
11     92200.71
1      89317.68
2      88366.32
4      83844.77
5      74509.89
Name: Order_Amount, dtype: float64

In [52]:
india_monthly_sales_df.idxmax()

np.int64(7)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order_ID                 30000 non-null  int64
 1   Customer_ID              30000 non-null  object
 2   Order_Date               30000 non-null  object
 3   Year                     30000 non-null  int64
 4   Month                    30000 non-null  int64
 5   Day                      30000 non-null  int64
 6   Day_Of_Week              30000 non-null  object
 7   Quarter                  30000 non-null  int64
 8   Customer_Age             30000 non-null  int64
 9   Customer_Gender          30000 non-null  object
 10  Country                  30000 non-null  object
 11  City                     30000 non-null  object
 12  Customer_Segment         30000 non-null  object
 13  Product_ID               30000 non-null  object
 14  Product_Category         30000 non-null  object
 15  Product_Subcategory      30000 non-null  object
 16  Brand                    30000 non-null  object
 17  Unit_Price               30000 non-null  float64
 18  Quantity                 30000 non-null  int64
 19  Discount_Percent         30000 non-null  int64
 20  Discount_Amount          30000 non-null  float64
 21  Coupon_Used              30000 non-null  object
 22  Shipping_Cost            30000 non-null  float64
 23  Tax_Amount               30000 non-null  float64
 24  Order_Amount             30000 non-null  float64
 25  Payment_Method           30000 non-null  object
 26  Device_Type              30000 non-null  object
 27  Traffic_Source           30000 non-null  object
 28  Membership_Status        30000 non-null  object
 29  Shipping_Method          30000 non-null  object
 30  Warehouse_Region         30000 non-null  object
 31  Delivery_Days            30000 non-null  int64
 32  Order_Status             30000 non-null  object
 33  Returned                 30000 non-null  object
 34  Review_Rating            30000 non-null  float64
 35  Customer_Lifetime_Value  30000 non-null  float64
 36  Profit_Margin_Percent    30000 non-null  float64
 37  Profit_Amount            30000 non-null  float64
 38  Season                   30000 non-null  object
 39  Holiday_Season           30000 non-null  object
 40  High_Value_Order         30000 non-null  object
dtypes: float64(9), int64(9), object(23)
memory usage: 9.4+ MB

Task 2 - Which Customer Segment generates the highest revenue?

In [55]:
df["Customer_Segment"].unique()

array(['Loyal', 'Returning', 'Premium', 'New'], dtype=object)

In [59]:
Highest_revenue = df.groupby("Customer_Segment")["Order_Amount"].sum()

In [60]:
Highest_revenue

Customer_Segment
Loyal        2659608.61
New          2982575.91
Premium      1145145.28
Returning    4582714.19
Name: Order_Amount, dtype: float64

In [63]:
Highest_revenue.sort_values(ascending=False)

Customer_Segment
Returning    4582714.19
New          2982575.91
Loyal        2659608.61
Premium      1145145.28
Name: Order_Amount, dtype: float64

In [64]:
df["Customer_Segment"].value_counts()

Customer_Segment
Returning    11987
New           7794
Loyal         7214
Premium       3005
Name: count, dtype: int64


lets check which customer_segement get high discount may be this will help that returing customer have high revenue

In [67]:
df.groupby("Customer_Segment")["Discount_Percent"].mean().sort_values(ascending=False)

Customer_Segment
New          12.705286
Loyal        12.660105
Returning    12.575707
Premium      12.465890
Name: Discount_Percent, dtype: float64

Lets check in which customer segement people spend more

In [69]:
df.groupby("Customer_Segment")["Order_Amount"].mean().sort_values(ascending=False)

Customer_Segment
New          382.675893
Returning    382.307015
Premium      381.079960
Loyal        368.673220
Name: Order_Amount, dtype: float64

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order_ID                 30000 non-null  int64
 1   Customer_ID              30000 non-null  object
 2   Order_Date               30000 non-null  object
 3   Year                     30000 non-null  int64
 4   Month                    30000 non-null  int64
 5   Day                      30000 non-null  int64
 6   Day_Of_Week              30000 non-null  object
 7   Quarter                  30000 non-null  int64
 8   Customer_Age             30000 non-null  int64
 9   Customer_Gender          30000 non-null  object
 10  Country                  30000 non-null  object
 11  City                     30000 non-null  object
 12  Customer_Segment         30000 non-null  object
 13  Product_ID               30000 non-null  object
 14  Product_Category         30000 non-null  object
 15  Product_Subcategory      30000 non-null  object
 16  Brand                    30000 non-null  object
 17  Unit_Price               30000 non-null  float64
 18  Quantity                 30000 non-null  int64
 19  Discount_Percent         30000 non-null  int64
 20  Discount_Amount          30000 non-null  float64
 21  Coupon_Used              30000 non-null  object
 22  Shipping_Cost            30000 non-null  float64
 23  Tax_Amount               30000 non-null  float64
 24  Order_Amount             30000 non-null  float64
 25  Payment_Method           30000 non-null  object
 26  Device_Type              30000 non-null  object
 27  Traffic_Source           30000 non-null  object
 28  Membership_Status        30000 non-null  object
 29  Shipping_Method          30000 non-null  object
 30  Warehouse_Region         30000 non-null  object
 31  Delivery_Days            30000 non-null  int64
 32  Order_Status             30000 non-null  object
 33  Returned                 30000 non-null  object
 34  Review_Rating            30000 non-null  float64
 35  Customer_Lifetime_Value  30000 non-null  float64
 36  Profit_Margin_Percent    30000 non-null  float64
 37  Profit_Amount            30000 non-null  float64
 38  Season                   30000 non-null  object
 39  Holiday_Season           30000 non-null  object
 40  High_Value_Order         30000 non-null  object
dtypes: float64(9), int64(9), object(23)
memory usage: 9.4+ MB

In [75]:
df.groupby("Customer_Segment")["Profit_Amount"].sum().sort_values(ascending=False)

Customer_Segment
Returning    888003.26
New          579346.30
Loyal        526075.50
Premium      222491.21
Name: Profit_Amount, dtype: float64

In [79]:
pd.crosstab(
    df["Customer_Segment"],
    df["Returned"],
)

Returned             No   Yes
Customer_Segment
Loyal              6491   723
New                6895   899
Premium            2725   280
Returning         10856  1131

In [81]:
pd.crosstab(
    df["Customer_Segment"],
    df["Returned"],
    normalize="index"
)*100

Returned                 No        Yes
Customer_Segment
Loyal             89.977821  10.022179
New               88.465486  11.534514
Premium           90.682196   9.317804
Returning         90.564779   9.435221

In [97]:
df[["Customer_Segment", "Quantity"]].head(10)

  Customer_Segment  Quantity
0            Loyal         3
1        Returning         1
2        Returning         3
3        Returning         3
4          Premium         1
5              New         3
6        Returning         3
7          Premium         1
8        Returning         1
9        Returning         5

In [100]:
df.groupby("Customer_Segment")["Quantity"].mean().sort_values(ascending=False)

Customer_Segment
Premium      3.106822
New          3.084937
Returning    3.078752
Loyal        3.068339
Name: Quantity, dtype: float64

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Order_ID                 30000 non-null  int64
 1   Customer_ID              30000 non-null  object
 2   Order_Date               30000 non-null  object
 3   Year                     30000 non-null  int64
 4   Month                    30000 non-null  int64
 5   Day                      30000 non-null  int64
 6   Day_Of_Week              30000 non-null  object
 7   Quarter                  30000 non-null  int64
 8   Customer_Age             30000 non-null  int64
 9   Customer_Gender          30000 non-null  object
 10  Country                  30000 non-null  object
 11  City                     30000 non-null  object
 12  Customer_Segment         30000 non-null  object
 13  Product_ID               30000 non-null  object
 14  Product_Category         30000 non-null  object
 15  Product_Subcategory      30000 non-null  object
 16  Brand                    30000 non-null  object
 17  Unit_Price               30000 non-null  float64
 18  Quantity                 30000 non-null  int64
 19  Discount_Percent         30000 non-null  int64
 20  Discount_Amount          30000 non-null  float64
 21  Coupon_Used              30000 non-null  object
 22  Shipping_Cost            30000 non-null  float64
 23  Tax_Amount               30000 non-null  float64
 24  Order_Amount             30000 non-null  float64
 25  Payment_Method           30000 non-null  object
 26  Device_Type              30000 non-null  object
 27  Traffic_Source           30000 non-null  object
 28  Membership_Status        30000 non-null  object
 29  Shipping_Method          30000 non-null  object
 30  Warehouse_Region         30000 non-null  object
 31  Delivery_Days            30000 non-null  int64
 32  Order_Status             30000 non-null  object
 33  Returned                 30000 non-null  object
 34  Review_Rating            30000 non-null  float64
 35  Customer_Lifetime_Value  30000 non-null  float64
 36  Profit_Margin_Percent    30000 non-null  float64
 37  Profit_Amount            30000 non-null  float64
 38  Season                   30000 non-null  object
 39  Holiday_Season           30000 non-null  object
 40  High_Value_Order         30000 non-null  object
dtypes: float64(9), int64(9), object(23)
memory usage: 9.4+ MB